---
title: "PEC2_M2.851_20201"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 1.Carga del fichero de Datos

```{r load_data}
library(readr)

data <- read_csv("train.csv", col_types = cols(Embarked = col_factor(levels = c("S", 
    "Q", "C")), PassengerId = col_integer(), 
    Pclass = col_factor(levels = c("1", "2", 
        "3")), Sex = col_factor(levels = c("male", 
        "female")), Survived = col_factor(levels = c("0", 
        "1"))))

View(data)
```

## 2. Descripción del Dataset

```{r}
str(data)
summary(data)
```

## 3.Búsqueda de Valores extremos

```{r Graphic Anlysis Extreme Values}
par(mfrow=c(1,2))
boxplot(data$Age, main="Age")
hist(data$Age, main="Age")

par(mfrow=c(1,2))
boxplot(data$Fare, main="Fare")
hist(data$Fare, main="Fare")

par(mfrow=c(1,2))
boxplot(data$SibSp, main="SibSp")
hist(data$SibSp, main="SibSp")

par(mfrow=c(1,2))
boxplot(data$Parch, main="Parch")
hist(data$Parch, main="Parch")
```

```{r}
table(data$Sex)
table(data$Survived)
```


## 4. Búsqueda de NA

```{r}
data_na<-colSums(is.na(data))
print(data_na)
barplot(data_na)
```

Reemplazamos los valores NA de la edad por la media
```{r}
data1<-data
data1$Age[is.na(data1$Age)]<-median(data$Age,na.rm=TRUE)
```


Reemplazamos los NA Embarked

```{r}
library(dplyr)
df2<-data %>% filter(!is.na(Embarked))
```


Analisis de correlación de valores númericos
```{r}
corrplot(cor(data[,6:8]), method = 'number')

```